name: Analysis_Agents_Concepts
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - alsa-lib=1.2.12
  - annotated-types=0.7.0
  - aom=3.9.1
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - blas=1.0
  - blosc=1.21.5
  - bokeh=3.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.14.4
  - ca-certificates=2024.7.4
  - cachetools=5.3.3
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorful=0.5.6
  - contourpy=1.2.1
  - cryptography=42.0.8
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - cycler=0.11.0
  - cytoolz=0.12.3
  - dask=2024.6.2
  - dask-core=2024.6.2
  - dask-expr=1.1.6
  - dask-glm=0.3.2
  - dask-ml=2024.4.4
  - dav1d=1.2.1
  - dbus=1.13.18
  - distlib=0.3.8
  - distributed=2024.6.2
  - dm-tree=0.1.8
  - expat=2.6.2
  - farama-notifications=0.0.4
  - ffmpeg=4.3
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.6.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.7.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-api-core=2.19.0
  - google-auth=2.30.0
  - googleapis-common-protos=1.63.1
  - gputil=1.4.0
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - gymnasium=0.28.1
  - h5py=3.11.0
  - harfbuzz=8.5.0
  - hdf5=1.12.1
  - icu=73.2
  - idna=3.7
  - imagecodecs=2024.6.1
  - imageio=2.34.1
  - importlib-metadata=7.2.0
  - importlib_metadata=7.2.0
  - importlib_resources=6.4.0
  - intel-openmp=2022.1.0
  - jax-jumpy=1.0.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.7
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcups=2.3.3
  - libcurand=10.3.6.39
  - libcurl=8.8.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=13.2.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.2
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm18=18.1.7
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.1
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightning-utilities=0.11.3.post0
  - llvm-openmp=14.0.6
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mdurl=0.1.2
  - memray=1.12.0
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.6
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - multipledispatch=0.6.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - nodejs=20.12.2
  - nomkl=2.0
  - nspr=4.35
  - nss=3.100
  - numba=0.60.0
  - numexpr=2.10.0
  - numpy=1.26.4
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.1.4
  - partd=1.4.2
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - ply=3.11
  - prometheus_client=0.20.0
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - py-cpuinfo=9.0.0
  - py-spy=0.3.14
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.7.4
  - pydantic-core=2.18.4
  - pygments=2.18.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.3.3
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - qhull=2020.2
  - qt-main=5.15.8
  - rav1e=0.6.6
  - ray-core=2.24.0
  - ray-data=2.24.0
  - ray-default=2.24.0
  - ray-rllib=2.24.0
  - ray-train=2.24.0
  - ray-tune=2.24.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.7.1
  - rpds-py=0.18.1
  - rsa=4.9
  - s2n=1.4.15
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - setproctitle=1.3.3
  - setuptools=69.5.1
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - smart_open=7.0.4
  - snappy=1.2.0
  - sortedcontainers=2.4.0
  - sparse=0.15.4
  - sqlite=3.45.3
  - svt-av1=2.1.0
  - sympy=1.12
  - tblib=3.0.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorboardx=2.6.2.2
  - textual=0.70.0
  - threadpoolctl=3.5.0
  - tifffile=2024.6.18
  - tk=8.6.14
  - toolz=0.12.1
  - torchaudio=2.3.1
  - torchmetrics=1.1.2
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - virtualenv=20.21.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.16.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.19.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - pygame==2.6.0
